---
name: dozzle
services:
  dozzle:
    image: amir20/dozzle:v10.9.0
    container_name: dozzle-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/config_storage/dozzle:/data
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_NO_ANALYTICS=true
    ports:
      - '0.0.0.0:7007:7007'
    networks:
      - intranet
    command: agent
    security_opt:
      - no-new-privileges:true  # helps to increase security

networks:
  intranet:
    external: true
