---
name: windows
services:
  windows:
    image: dockurr/windows:6.06
    container_name: windows
    volumes:
      - /data/config_storage/windows:/storage
    environment:
      VERSION: "11"
    ports:
      #- 8006:8006  # webui
      - '0.0.0.0:3389:3389/tcp'
      - '0.0.0.0:3389:3389/udp'
    networks:
      - intranet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.windows.entrypoints=http"
      - "traefik.http.routers.windows.rule=Host(`windows.${DOMAIN}`)"
      - "traefik.http.middlewares.windows-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.windows.middlewares=windows-https-redirect"
      - "traefik.http.routers.windows-secure.entrypoints=https"
      - "traefik.http.routers.windows-secure.rule=Host(`windows.${DOMAIN}`)"
      - "traefik.http.routers.windows-secure.tls=true"
      - "traefik.http.routers.windows-secure.service=windows"
      - "traefik.http.services.windows.loadbalancer.server.port=8006"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=windows"
      - "homepage.icon=/images/windows.png"
      - "homepage.href=https://windows.${DOMAIN}/"
      - "traefik.http.routers.windows-secure.middlewares=tinyauth"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm
      - /dev/net/tun
    security_opt:
      - no-new-privileges:true  # helps to increase security
    stop_grace_period: 2m

networks:
  intranet:
    external: true
