---
name: docmost
services:
  docmost:
    image: docmost/docmost:0.90.1
    container_name: docmost
    depends_on:
      - docmost_postgres
      - docmost_redis
    volumes:
      - /data/config_storage/docmost/storage:/app/data/storage
    environment:
      APP_URL: "https://docmost.${DOMAIN}"
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "postgresql://docmost:${POSTGRES_PASSWORD}@docmost_postgres:5432/docmost"
      REDIS_URL: "redis://docmost_redis:6379"
    ports:
      - '0.0.0.0:3006:3000'
    networks:
      - intranet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docmost.entrypoints=http"
      - "traefik.http.routers.docmost.rule=Host(`docmost.${DOMAIN}`)"
      - "traefik.http.middlewares.docmost-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.docmost.middlewares=docmost-https-redirect"
      - "traefik.http.routers.docmost-secure.entrypoints=https"
      - "traefik.http.routers.docmost-secure.rule=Host(`docmost.${DOMAIN}`)"
      - "traefik.http.routers.docmost-secure.tls=true"
      - "traefik.http.routers.docmost-secure.service=docmost"
      - "traefik.http.services.docmost.loadbalancer.server.port=3000"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=docmost"
      - "homepage.icon=/images/docmost.png"
      - "homepage.href=https://docmost.${DOMAIN}/"
    user: 1000:1000
    security_opt:
      - no-new-privileges:true  # helps to increase security

  docmost_postgres:
    image: postgres:18.6
    container_name: docmost_postgres
    volumes:
      - /data/config_storage/docmost/db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - intranet
    restart: unless-stopped
    user: 1000:1000
    security_opt:
      - no-new-privileges:true  # helps to increase security

  docmost_redis:
    image: redis:8.10.0
    container_name: docmost_redis
    volumes:
      - /data/config_storage/docmost/redis_data:/data
    networks:
      - intranet
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    user: 1000:1000
    security_opt:
      - no-new-privileges:true  # helps to increase security

networks:
  intranet:
    external: true
