---
name: periphery
services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2.3.3
    container_name: periphery
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /opt/config_storage/komodo/etc_komodo:/etc/komodo
      - /opt/config_storage/komodo/periphery-keys:/config/keys
    environment:
      PERIPHERY_CORE_ADDRESS: 10.1.1.65:9120
      PERIPHERY_CONNECT_AS: openwrt
      PERIPHERY_ONBOARDING_KEY: ${PERIPHERY_ONBOARDING_KEY}
      PERIPHERY_CORE_PUBLIC_KEYS: file:/config/keys/core.pub
      PERIPHERY_DISABLE_TERMINALS: false
      PERIPHERY_DISABLE_CONTAINER_EXEC: false
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
    ports:
      - 8120:8120
    network_mode: host
    restart: always
    logging:
      driver: local
    labels:
      komodo.skip:
    init: true
    security_opt:
      - no-new-privileges:true  # helps to increase security

networks:
  intranet:
    external: true
