services:
  keeper:
    image: ghcr.io/ridafkih/keeper-standalone:2.10.1
    volumes:
      - /data/config_storage/keeper:/var/lib/postgresql/data
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      TRUSTED_ORIGINS: https://keeper.${DOMAIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keeper.entrypoints=http"
      - "traefik.http.routers.keeper.rule=Host(`keeper.${DOMAIN}`)"
      - "traefik.http.middlewares.keeper-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.keeper.middlewares=keeper-https-redirect"
      - "traefik.http.routers.keeper-secure.entrypoints=https"
      - "traefik.http.routers.keeper-secure.rule=Host(`keeper.${DOMAIN}`)"
      - "traefik.http.routers.keeper-secure.tls=true"
      - "traefik.http.routers.keeper-secure.service=keeper"
      - "traefik.http.services.keeper.loadbalancer.server.port=80"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=keeper"
      - "homepage.icon=/images/keeper.png"
      - "homepage.href=https://keeper.${DOMAIN}/"

networks:
  intranet:
    external: true
