---
name: chhoto-url
services:
  chhoto-url:
    image: sintan1729/chhoto-url:7.5.3
    container_name: chhoto-url
    volumes:
      - /data/config_stortage/chhoto-url:/data
    environment:
      - CHHOTO_DB_URL=/data/urls.sqlite
      - CHHOTO_SQLITE_USE_WAL_MODE=True
      - CHHOTO_SITE_URL=https://l.s8di.com
      - CHHOTO_REDIRECT_METHOD=TEMPORARY
      - CHHOTO_SLUG_STYLE=UID
      - CHHOTO_SLUG_LENGTH=8
      - CHHOTO_HASH_ALGORITHM=Argon2
      - password=$$argon2id$$v=19$$m=65536,t=3,p=1$$Ym9oc2F4NG5pOGs4NzJ1dw$$9BH1GtM1+2U4yF15t9sHJsqOlyu5dVPmt1tOaOsFIk4
    ports:
      - '0.0.0.0:34789:4567'
    networks:
      - intranet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chhoto.entrypoints=http"
      - "traefik.http.routers.chhoto.rule=Host(`chhoto.${DOMAIN}`)"
      - "traefik.http.middlewares.chhoto-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.chhoto.middlewares=chhoto-https-redirect"
      - "traefik.http.routers.chhoto-secure.entrypoints=https"
      - "traefik.http.routers.chhoto-secure.rule=Host(`chhoto.${DOMAIN}`)"
      - "traefik.http.routers.chhoto-secure.tls=true"
      - "traefik.http.routers.chhoto-secure.service=chhoto"
      - "traefik.http.services.chhoto.loadbalancer.server.port=4567"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=URL Shortener"
      - "homepage.icon=/images/chhoto.png"
      - "homepage.href=https://chhoto.${DOMAIN}/"
      - "traefik.http.routers.chhoto-secure.middlewares=tinyauth"
    user: 1000:1000
    cap_drop:
      - ALL
    dns:
      - 0.0.0.0
    read_only: true
    security_opt:
      - no-new-privileges:true  # helps to increase security

networks:
  intranet:
    external: true
