---
services:
  filebrowser:
    volumes:
      - /data/mnt/shows:/srv/data/plex
      - /data/config_storage/all_mck:/srv/data/all_mck:ro
      - /data/dont_backup/:/srv/data/dont_backup
      - /data/config_storage/filebrowserquantum/config.yaml:/home/filebrowser/config.yaml
      - /data/config_storage/filebrowserquantum/database.db:/home/filebrowser/database.db
    user: 1000:1000
    ports:
      - 12170:80
    image: gtstef/filebrowser:1.2.3-stable
    environment:
      - FILEBROWSER_ADMIN_PASSWORD=${FILEBROWSER_ADMIN_PASSWORD}
      - FILEBROWSER_DATABASE=/home/filebrowser/database.db
      - FILEBROWSER_CONFIG=/home/filebrowser/config.yaml
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teachers.entrypoints=http"
      - "traefik.http.routers.teachers.rule=Host(`teachers.${DOMAIN}`)"
      - "traefik.http.middlewares.teachers-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.teachers.middlewares=teachers-https-redirect"
      - "traefik.http.routers.teachers-secure.entrypoints=https"
      - "traefik.http.routers.teachers-secure.rule=Host(`teachers.${DOMAIN}`)"
      - "traefik.http.routers.teachers-secure.tls=true"
      - "traefik.http.routers.teachers-secure.service=teachers"
      - "traefik.http.services.teachers.loadbalancer.server.port=80"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=teachers"
      - "homepage.icon=/images/files.png"
      - "homepage.href=https://teachers.${DOMAIN}/"

networks:
  intranet:
    external: true
