---
services:
  filebrowser:
    volumes:
      - /data:/srv/data/data
      - /data/mnt/shows:/srv/data/shows
      - /data/mnt/movies:/srv/data/movies
      - /data/mnt/youtube:/srv/data/youtube
      - /data/music:/srv/data/music
      - /data/audiobooks:/srv/data/audiobooks
      - /data/ebooks:/srv/data/ebooks
      - /data/mnt/torrents:/srv/data/torrents
      - /data/config_storage/all_mck:/srv/data/shows/all_mck_teacher_files:ro
      - /data/config_storage/all_mck:/srv/data/all_mck:ro
      - /data/dont_backup/:/srv/data/dont_backup
      - /data/config_storage/filebrowserquantum/config.yaml:/home/filebrowser/config.yaml
      - /data/config_storage/filebrowserquantum/database.db:/home/filebrowser/database.db
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 12170:80
    image: gtstef/filebrowser:1.5.0-stable
    container_name: filebrowserquantum
    environment:
      - FILEBROWSER_ADMIN_PASSWORD=${FILEBROWSER_ADMIN_PASSWORD}
      - FILEBROWSER_DATABASE=/home/filebrowser/database.db
      - FILEBROWSER_CONFIG=/home/filebrowser/config.yaml
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.files2.entrypoints=http"
      - "traefik.http.routers.files2.rule=Host(`files2.${DOMAIN}`)"
      - "traefik.http.middlewares.files2-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.files2.middlewares=files2-https-redirect"
      - "traefik.http.routers.files2-secure.entrypoints=https"
      - "traefik.http.routers.files2-secure.rule=Host(`files2.${DOMAIN}`)"
      - "traefik.http.routers.files2-secure.tls=true"
      - "traefik.http.routers.files2-secure.service=files2"
      - "traefik.http.services.files2.loadbalancer.server.port=80"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Media"
      - "homepage.name=files2"
      - "homepage.icon=/images/files.png"
      - "homepage.href=https://files2.${DOMAIN}/"

networks:
  intranet:
    external: true
