services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:3.2.0
    container_name: immich-public-proxy
    restart: unless-stopped
    ports:
      - "8408:3000"
    environment:
      PUBLIC_BASE_URL: https://photos.shadybraden.com
      IMMICH_URL: https://immich.${DOMAIN}
      CONFIG: |
        {
          "ipp": {
            "showHomePage": true,
            "allowDownload": true
          }
        }
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
    dns:
      - ${DNS_SERVER1}
      - ${DNS_SERVER2}
