name: immich-public-proxy
services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:3.2.1
    container_name: immich-public-proxy
    environment:
      PUBLIC_BASE_URL: https://photos.shadybraden.com
      IMMICH_URL: https://immich.${DOMAIN}
      CONFIG: |
        {
          "ipp": {
            "showHomePage": true,
            "allowDownload": true
          }
        }
    ports:
      - '0.0.0.0:8408:3000'
    restart: unless-stopped
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
    dns:
      - ${DNS_SERVER1}
      - ${DNS_SERVER2}
