services:
  immich_kiosk:
    image: ghcr.io/damongolding/immich-kiosk:0.39.3
    container_name: immich_kiosk
    user: 1000:1000
    environment:
      LANG: "en_US"
      TZ: America/New_York
      KIOSK_IMMICH_API_KEY: "${immich_api_key}"
      KIOSK_IMMICH_URL: "immich.${DOMAIN}"
      KIOSK_ALBUMS: "fda3df75-a684-4a03-8a83-6aee232897e4"
    volumes:
      - /data/config_storage/immich_kiosk:/config
      - /data/config_storage/komodo/etc_komodo/repos/compose_main/immich_kiosk/config.yaml:/config/config.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/kiosk", "--healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich_kiosk.entrypoints=http"
      - "traefik.http.routers.immich_kiosk.rule=Host(`immich_kiosk.${DOMAIN}`)"
      - "traefik.http.middlewares.immich_kiosk-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.immich_kiosk.middlewares=immich_kiosk-https-redirect"
      - "traefik.http.routers.immich_kiosk-secure.entrypoints=https"
      - "traefik.http.routers.immich_kiosk-secure.rule=Host(`immich_kiosk.${DOMAIN}`)"
      - "traefik.http.routers.immich_kiosk-secure.tls=true"
      - "traefik.http.routers.immich_kiosk-secure.service=immich_kiosk"
      - "traefik.http.services.immich_kiosk.loadbalancer.server.port=3000"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=immich_kiosk"
      - "homepage.icon=/images/immich_kiosk.png"
      - "homepage.href=https://immich_kiosk.${DOMAIN}/"

networks:
  intranet:
    external: true
