name: Lint

on:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: tools_container
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: docker-compose-linter/dclint-github-action@v3.1.0
        with:
          path: ./
          recursive: true
