---
services:
  wg-easy_vpn:
    image: ghcr.io/wg-easy/wg-easy:15.2.2
    container_name: wg-easy_vpn
    environment:
      WG_DEVICE: enp2s0  # https://github.com/wg-easy/wg-easy/issues/1795#issuecomment-2900911182
      INSECURE: true
    networks:
      wg_vpn:
        ipv4_address: 10.22.22.22
    volumes:
      - /data/config_storage/wg-easy_vpn:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51822:51822/udp"  # public port. remember to port forward this
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

networks:
  wg_vpn:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.22.22.0/24
