---
name: mmich-machine-learning
services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v3.2.0
    container_name: immich_machine_learning
    volumes:
      - /data/dont_backup/immich_machine_learning:/cache
    ports:
      - '0.0.0.0:3003:3003'
    restart: unless-stopped
