---
name: dnscrypt-proxy
services:
  dnscrypt-proxy:
    image: klutchell/dnscrypt-proxy:v2.1.18
    container_name: dnscrypt
    volumes:
      - /data/config_storage/dnscrypt/logs:/logs
      - /data/config_storage/dnscrypt/config:/config
      #- /data/config_storage/komodo/etc_komodo/repos/compose_main/dnscrypt-proxy/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml:ro
    ports:
      - '0.0.0.0:5053:5053/udp'
      - '0.0.0.0:5053:5053/tcp'
    restart: always
