---
services:
  pihole:
    image: pihole/pihole:2026.05.0
    container_name: pihole
    network_mode: host
    environment:
      - FTLCONF_webserver_api_password=${pihole_password}
      - TZ=America/New_York
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_webserver_port=0.0.0.0:8082
      - FTLCONF_dns_upstreams="192.168.50.1#5053"  # dnscrypt-proxy
      - PIHOLE_UID=0
      - PIHOLE_GID=0
    volumes:
      - /opt/config_storage/pihole/etc-pihole:/etc/pihole
      - /opt/config_storage/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - /opt/config_storage/pihole/var:/var
      - /opt/config_storage/pihole/var/run:/var/run
    restart: no
    cap_add:
      - SYS_NICE
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_TIME
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80/tcp"  # web ui
    security_opt:
      - no-new-privileges:true  # helps to increase security
