---
services:
  pihole:
    image: pihole/pihole:2026.07.2
    container_name: pihole
    network_mode: host
    environment:
      - FTLCONF_webserver_api_password=${pihole_password}
      - TZ=America/New_York
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_webserver_port=8082
      - FTLCONF_dns_upstreams=10.1.1.1#5053  # dnscrypt-proxy
      - PIHOLE_UID=0
      - PIHOLE_GID=0
    volumes:
      - /opt/config_storage/pihole/etc-pihole:/etc/pihole
      - /opt/config_storage/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: always
    cap_add:
      - SYS_NICE
      - NET_BIND_SERVICE
      - SYS_TIME
      - NET_ADMIN
      - CHOWN
    security_opt:
      - no-new-privileges:true  # helps to increase security
