---
name: immich-public
services:
  immich-server-public:
    container_name: immich_server-public
    image: ghcr.io/immich-app/immich-server:v3.1.0
    volumes:
      - /data/config_storage/immich-public/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - /etc/komodo/env/immich-public-holmie.env
    depends_on:
      - redis-public
      - database-public
    ports:
      - '8408:2283'
    restart: no
    healthcheck:
      disable: false
    environment:
      - IMMICH_TRUSTED_PROXIES=172.0.0.0/8
      - DB_HOSTNAME=database-public
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich-public.entrypoints=http"
      - "traefik.http.routers.immich-public.rule=Host(`immich-public.${DOMAIN}`)"
      - "traefik.http.middlewares.immich-public-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.immich-public.middlewares=immich-public-https-redirect"
      - "traefik.http.routers.immich-public-secure.entrypoints=https"
      - "traefik.http.routers.immich-public-secure.rule=Host(`immich-public.${DOMAIN}`)"
      - "traefik.http.routers.immich-public-secure.tls=true"
      - "traefik.http.routers.immich-public-secure.service=immich-public"
      - "traefik.http.services.immich-public.loadbalancer.server.port=2283"  # port of the service
      - "traefik.docker.network=intranet"
      - "homepage.group=Media"
      - "homepage.name=immich-public"
      - "homepage.icon=/images/immich.png"
      - "homepage.href=https://immich-public.${DOMAIN}/"

  immich-machine-learning-public:
    container_name: immich_machine_learning-public
    image: ghcr.io/immich-app/immich-machine-learning:v3.1.0
    volumes:
      - model-cache-public:/cache
    env_file:
      - /etc/komodo/env/immich-public-holmie.env
    restart: no
    networks:
      - intranet
    healthcheck:
      disable: false

  redis-public:
    container_name: immich_redis-public
    image: docker.io/valkey/valkey:8.1.9  # check: https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
    restart: no
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - intranet

  database-public:
    container_name: immich_postgres-public
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS='--data-checksums'
    volumes:
      - /data/config_storage/immich-public/postgres:/var/lib/postgresql/data
    restart: no
    networks:
      - intranet

volumes:
  model-cache-public:

networks:
  intranet:
    external: true
