---
services:
  zot:
    image: ghcr.io/project-zot/zot:v2.1.16
    container_name: zot_registry
    user: 1000:1000
    volumes:
      - /data/config_storage/zot:/tmp/zot
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oci.entrypoints=http"
      - "traefik.http.routers.oci.rule=Host(`oci.${DOMAIN}`)"
      - "traefik.http.middlewares.oci-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.oci.middlewares=oci-https-redirect"
      - "traefik.http.routers.oci-secure.entrypoints=https"
      - "traefik.http.routers.oci-secure.rule=Host(`oci.${DOMAIN}`)"
      - "traefik.http.routers.oci-secure.tls=true"
      - "traefik.http.routers.oci-secure.service=oci"
      - "traefik.http.services.oci.loadbalancer.server.port=5000"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=zot"
      - "homepage.icon=/images/zot.png"
      - "homepage.href=https://oci.${DOMAIN}/"

networks:
  intranet:
    external: true
