---
services:
  obs-studio-otel:
    image:  ghcr.io/sam-delap/obs-studio-otel:2.0.1
    environment:
      - OTEL_SERVICE_NAME=obs-studio-scraper
      - SCRAPE_INTERVAL_SECONDS=5
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - 'OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-ingester:4317'
      - OBS_PASSWORD=${OBS_PASSWORD}
      - OBS_PORT=4455
      - OBS_HOST=192.168.1.45
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - signoz-network
    container_name: obs-otel
networks:
  signoz-network:
    external: true
