---
name: infisical
services:
  backend:
    image: infisical/infisical:v0.163.0
    container_name: infisical-backend
    depends_on:
      infisical-db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - NODE_ENV=production
      - AUTH_SECRET=${AUTH_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - REDIS_URL=redis://redis:6379
      - SITE_URL=https://infisical.${DOMAIN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_CONNECTION_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@infisical-db:5432/${POSTGRES_DB}
    networks:
      - intranet
      - infisical
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.infisical.entrypoints=http"
      - "traefik.http.routers.infisical.rule=Host(`infisical.${DOMAIN}`)"
      - "traefik.http.middlewares.infisical-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.infisical.middlewares=infisical-https-redirect"
      - "traefik.http.routers.infisical-secure.entrypoints=https"
      - "traefik.http.routers.infisical-secure.rule=Host(`infisical.${DOMAIN}`)"
      - "traefik.http.routers.infisical-secure.tls=true"
      - "traefik.http.routers.infisical-secure.service=infisical"
      - "traefik.http.services.infisical.loadbalancer.server.port=8080"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=infisical"
      - "homepage.icon=/images/infisical.png"
      - "homepage.href=https://infisical.${DOMAIN}/"
    user: 1000:1000
    security_opt:
      - no-new-privileges:true  # helps to increase security
      #- "traefik.http.routers.infisical-secure.middlewares=tinyauth"

  infisical-db:
    image: postgres:14.24-alpine3.24  # pinned to 14-alpine - https://raw.githubusercontent.com/Infisical/infisical/main/docker-compose.prod.yml
    container_name: infisical-db
    volumes:
      - /data/config_storage/infisical/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - NODE_ENV=production
      - AUTH_SECRET=${AUTH_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - REDIS_URL=redis://redis:6379
      - SITE_URL=https://infisical.${DOMAIN}
    networks:
      - intranet
      - infisical
    restart: unless-stopped
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10
    user: 1000:1000
    security_opt:
      - no-new-privileges:true  # helps to increase security

  redis:
    image: redis:8.10.1  # use latest
    container_name: infisical-dev-redis
    volumes:
      - /data/config_storage/infisical/redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - NODE_ENV=production
      - AUTH_SECRET=${AUTH_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - REDIS_URL=redis://redis:6379
      - SITE_URL=https://infisical.${DOMAIN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_CONNECTION_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - intranet
      - infisical
    restart: unless-stopped
    user: 1000:1000
    security_opt:
      - no-new-privileges:true  # helps to increase security

networks:
  infisical:
  intranet:
    external: true