---
services:
  loggifly:
    image: ghcr.io/clemcer/loggifly:v2.0.0
    container_name: loggifly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:  # https://clemcer.github.io/loggifly/guide/environment-variables.html
      NTFY_URL: "https://ntfy.holmlab.org"  # not a variable because logs should all go back to holmlab
      NTFY_TOPIC: ${topic}
      TITLE_TEMPLATE: "{{ container_name }}, {{ keyword }}"
      SYSTEM_NOTIFICATIONS_START: true
      SYSTEM_NOTIFICATIONS_SHUTDOWN: false
      SYSTEM_NOTIFICATIONS_MONITOR_EVENT: false
      TRIGGER_COOLDOWN: 5
      #CONTAINERS: "vaultwarden,filebrowserquantum,actual_server,audiobookshelf,autobrr,baikal,beszel,bichon"
      CONTAINERS: "*"
      CONTAINERS_NEVER_MONITOR: "loggifly-errors,loggifly,skywatch,renovate"
      GLOBAL_KEYWORDS: "login?username=,failed login,password,Authentication failed,Failed authentication attempt,Wrong credentials,Invalid credentials,AuthenticationFailed"
      IGNORE_KEYWORDS: "purging password reset tokens"
      #GLOBAL_KEYWORDS_WITH_ATTACHMENT: "critical"  # Attaches a log file to the notification
      NTFY_PRIORITY: 2
    restart: unless-stopped
