---
services:
  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    command: tunnel --no-autoupdate run --token ${token}
    networks:
      - intranet
    restart: unless-stopped

networks:
  intranet:
    external: true
