---
name: cloudflared
services:
  cloudflared:
    image: cloudflare/cloudflared:2026.8.2
    container_name: cloudflared
    networks:
      - intranet
    command: tunnel --no-autoupdate run --token ${token}
    restart: unless-stopped

networks:
  intranet:
    external: true
