---
name: linkwarden
services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:v2.16.1
    container_name: linkwarden
    depends_on:
      - postgres
    volumes:
      - /data/config_storage/linkwarden/data:/data/data
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    networks:
      - intranet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.links.entrypoints=http"
      - "traefik.http.routers.links.rule=Host(`links.${DOMAIN}`)"
      - "traefik.http.middlewares.links-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.links.middlewares=links-https-redirect"
      - "traefik.http.routers.links-secure.entrypoints=https"
      - "traefik.http.routers.links-secure.rule=Host(`links.${DOMAIN}`)"
      - "traefik.http.routers.links-secure.tls=true"
      - "traefik.http.routers.links-secure.service=links"
      - "traefik.http.services.links.loadbalancer.server.port=3000"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=Linkwarden"
      - "homepage.icon=/images/linkwarden.png"
      - "homepage.href=https://links.${DOMAIN}/"
    security_opt:
      - no-new-privileges:true  # helps to increase security

  postgres:
    image: postgres:16.15-alpine  # pined to 16-alpine - https://github.com/linkwarden/linkwarden/blob/main/docker-compose.yml
    container_name: linkwarden_postgres
    volumes:
      - /data/config_storage/linkwarden/pgdata:/var/lib/postgresql/data
    networks:
      - intranet
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true  # helps to increase security

networks:
  intranet:
    external: true
