---
services:
  madblog:
    image: quay.io/blacklight/madblog
    volumes:
      - /data/config_storage/madblog:/data
    environment:
      - MADBLOG_ENABLE_WEBMENTIONS=0
    ports:
      - 8000:8000
    user: 1000:1000
