---
name: skywatch
services:
  skywatch:
    image: git.holmlab.org/shady/skywatch:1.5.7
    container_name: skywatch
    volumes:
      - /data/config_storage/recents.txt:/app/recents.txt
    stdin_open: true
    tty: true
