services:
  mariadb_memtly:
    container_name: 'mariadb_memtly'
    image: mariadb:11.4.12  # use latest
    user: 0:0
    ports:
      - '3306:3306/tcp'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'memtly'
      MYSQL_USER: 'memtly'
      MYSQL_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      TZ: 'America/New_York'
    volumes:
      - /data/config_storage/memtly/data-volume-mariadb:/var/lib/mysql:rw
    networks:
      - memtly-net
      - intranet
    hostname: 'mariadb_memtly'
    restart: no
  memtly:
    container_name: Memtly
    image: memtly/memtly:1.0.3
    user: 0:0
    ports:
      - '8408:5000/tcp'
    environment:
      TITLE: 'Memories'
      DATABASE_TYPE: 'mariadb'
      DATABASE_CONNECTION_STRING: 'Server=mariadb_memtly;Port=3306;Database=memtly;User=memtly;Password=${MYSQL_ROOT_PASSWORD};'
      ACCOUNT_ADMIN_PASSWORD: '${ACCOUNT_ADMIN_PASSWORD}'
      ENCRYPTION_KEY: '${ENCRYPTION_KEY}'
      ENCRYPTION_SALT: '${ENCRYPTION_SALT}'
    volumes:
      - /data/config_storage/memtly/data-volume-config:/app/config
      - /data/config_storage/memtly/data-volume-thumbnails:/app/thumbnails
      - /data/config_storage/memtly/data-volume-uploads:/app/uploads
      - /data/config_storage/memtly/data-volume-custom-resources:/app/custom_resources
    networks:
      - memtly-net
      - intranet
    hostname: memtly
    restart: no
    depends_on:
      - mariadb_memtly
    security_opt:
      - no-new-privileges:true  # helps to increase security
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memtly.entrypoints=http"
      - "traefik.http.routers.memtly.rule=Host(`memtly.${DOMAIN}`)"
      - "traefik.http.middlewares.memtly-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.memtly.middlewares=memtly-https-redirect"
      - "traefik.http.routers.memtly-secure.entrypoints=https"
      - "traefik.http.routers.memtly-secure.rule=Host(`memtly.${DOMAIN}`)"
      - "traefik.http.routers.memtly-secure.tls=true"
      - "traefik.http.routers.memtly-secure.service=memtly"
      - "traefik.http.services.memtly.loadbalancer.server.port=5000"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=memtly"
      - "homepage.icon=/images/memtly.png"
      - "homepage.href=https://memtly.${DOMAIN}/"

networks:
  intranet:
    external: true
  memtly-net:
    name: 'memtly-net'
    external: false
