---
services:
  metube:
    image: ghcr.io/alexta69/metube:2026.04.02
    container_name: metube
    restart: unless-stopped
    volumes:
      - /data/mnt/youtube:/downloads  # so jellyfin can access
    security_opt:
      - no-new-privileges:true  # helps to increase security
    network_mode: container:gluetun
    labels:
      - "homepage.group=Other"
      - "homepage.name=metube"
      - "homepage.icon=/images/metube.png"
      - "homepage.href=https://metube.${DOMAIN}/"

networks:
  intranet:
    external: true
