---
name: syncthing
services:
  syncthing:
    image: quay.io/linuxserver.io/syncthing:2.1.5
    container_name: syncthing
    volumes:
      - /data/config_storage/syncthing/config:/config
      - /data/config_storage/syncthing/syncthing:/var/syncthing
      - /data/mnt:/mnt
      - /data/config_storage/seedvault:/seedvault
      - /data/music:/music
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - '0.0.0.0:8384:8384'  # web ui
      - '0.0.0.0:21027:21027/udp'
      - '0.0.0.0:22000:22000/tcp'
      - '0.0.0.0:22000:22000/udp'
    networks:
      - intranet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing-holmie.entrypoints=http"
      - "traefik.http.routers.syncthing-holmie.rule=Host(`syncthing-holmie.${DOMAIN}`)"
      - "traefik.http.middlewares.syncthing-holmie-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.syncthing-holmie.middlewares=syncthing-holmie-https-redirect"
      - "traefik.http.routers.syncthing-holmie-secure.entrypoints=https"
      - "traefik.http.routers.syncthing-holmie-secure.rule=Host(`syncthing-holmie.${DOMAIN}`)"
      - "traefik.http.routers.syncthing-holmie-secure.tls=true"
      - "traefik.http.routers.syncthing-holmie-secure.service=syncthing-holmie"
      - "traefik.http.services.syncthing-holmie.loadbalancer.server.port=8384"  # port of the service
      - "traefik.docker.network=intranet"
      - "homepage.group=Background-stuff"
      - "homepage.name=syncthing"
      - "homepage.icon=/images/syncthing.png"
      - "homepage.href=https://syncthing-holmie.${DOMAIN}/"
    dns:
      - ${DNS_SERVER1}
      - ${DNS_SERVER2}
    hostname: syncthing
    security_opt:
      - no-new-privileges:true  # helps to increase security

networks:
  intranet:
    external: true
