---
# merge the pr made by renovate first
# updates komodo and periphery on all hosts
# init with `ansible-galaxy collection install community.docker`
- name: Deploy periphery on shady
  hosts: shady@10.1.1.16
  become: false

  vars:
    compose_dir: /data/config_storage/compose/periphery
  tasks:
    - name: Git pull latest changes
      ansible.builtin.shell:
        cmd: git pull
        chdir: "{{ compose_dir }}"

    - name: docker compose up -d
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: present
        pull: missing
      become: true
