---
- name: Install Podman
  hosts: podman
  become: false

  tasks:
    - name: Setup
      block:
      - name: Update apt cache
        ansible.builtin.apt:
          update_cache: true
        become: true
        when: ansible_os_family == "Debian"

      - name: Install podman
        ansible.builtin.apt:
          name: podman
          state: present
        become: true
        when: ansible_os_family == "Debian"

      - name: Start podman.socket
        ansible.builtin.systemd:
          name: podman.socket
          enabled: true
          state: started
          scope: user

      - name: Create intranet network
        containers.podman.podman_network:
          name: intranet
          state: present

      - name: Clone podman repo
        ansible.builtin.git:
          repo: https://git.holmlab.org/shady/compose
          dest: ~/config_storage/compose
          version: main
          update: true

    - name: Deploy OpenWebUI
      ansible.builtin.command: podman compose -f ~/config_storage/compose/openwebui/podman.yaml up -d
