---
- name: Install Podman
  hosts: podman
  become: false

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"

    - name: Install podman
      ansible.builtin.apt:
        name: podman
        state: present
      become: true
      when: ansible_os_family == "Debian"
