---
name: kener
services:
  kener:
    image: rajnandan1/kener:v4.1.5
    container_name: kener
    volumes:
      - /data/config_storage/kener/database:/app/database
    environment:
      KENER_SECRET_KEY: ${KENER_SECRET_KEY}
      ORIGIN: "https://kener.${DOMAIN}"
    networks:
      - intranet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kener.entrypoints=http"
      - "traefik.http.routers.kener.rule=Host(`kener.${DOMAIN}`)"
      - "traefik.http.middlewares.kener-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kener.middlewares=kener-https-redirect"
      - "traefik.http.routers.kener-secure.entrypoints=https"
      - "traefik.http.routers.kener-secure.rule=Host(`kener.${DOMAIN}`)"
      - "traefik.http.routers.kener-secure.tls=true"
      - "traefik.http.routers.kener-secure.service=kener"
      - "traefik.http.services.kener.loadbalancer.server.port=3000"  # port of the service
      - "traefik.docker.network=intranet"
      - "homepage.group=Infrastructure"
      - "homepage.name=Kener"
      - "homepage.icon=/images/kener.png"
      - "homepage.href=https://kener.${DOMAIN}/"
      - env=production
    dns:
      - ${DNS_SERVER1}
      - ${DNS_SERVER2}
    security_opt:
      - no-new-privileges:true  # helps to increase security

networks:
  intranet:
    external: true