services:
  postgres:
    container_name: repsy-postgres
    hostname: repsy-postgres
    image: postgres:18
    environment:
      - POSTGRES_DB=repsy
      - POSTGRES_USER=repsy
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet

  repsy:
    container_name: repsy
    image: repo.repsy.io/repsy/os/repsy:26.03.0
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_URL=jdbc:postgresql://repsy-postgres:5432/repsy
      - DB_USERNAME=repsy
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_INITIAL_PASSWORD=${ADMIN_INITIAL_PASSWORD}
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.entrypoints=http"
      - "traefik.http.routers.registry.rule=Host(`registry.${DOMAIN}`)"
      - "traefik.http.middlewares.registry-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.registry.middlewares=registry-https-redirect"
      - "traefik.http.routers.registry-secure.entrypoints=https"
      - "traefik.http.routers.registry-secure.rule=Host(`registry.${DOMAIN}`)"
      - "traefik.http.routers.registry-secure.tls=true"
      - "traefik.http.routers.registry-secure.service=registry"
      - "traefik.http.services.registry.loadbalancer.server.port=8080"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=registry"
      - "homepage.icon=/images/registry.png"
      - "homepage.href=https://registry.${DOMAIN}/"

networks:
  intranet:
    external: true
