---
services:
    nginx:
        image: 'nginx:alpine'
        container_name: hugo-server
        volumes:
            - '/data/hugo-public:/usr/share/nginx/html:ro'
        ports:
            - '8089:80'
